### ISSUE TITLE
simple request keeps returning `not solved`

### ISSUE THREAD

**Issue by longinteger017** [a-maliarov/amazoncaptcha#27]
The following keeps returning **Not solved** for me. I have never got any other return.
```
import selenium
from amazoncaptcha import AmazonCaptcha
from selenium import webdriver as webdriver

d = webdriver.Chrome(ChromeDriverManager().install())
captcha = AmazonCaptcha.fromdriver(d)
print(captcha.solve(keep_logs=True))
```

not-solved-captcha.log:
https://images-na.ssl-images-amazon.com/captcha/bfhuzdtn/Captcha_cebmxydbrt.jpg
https://images-na.ssl-images-amazon.com/captcha/perumqgc/Captcha_gaommpndkq.jpg
https://images-na.ssl-images-amazon.com/captcha/rhnrlggh/Captcha_tijaodpupx.jpg
https://images-na.ssl-images-amazon.com/captcha/bysppkyq/Captcha_xroxbnvmrg.jpg

**Comment by a-maliarov** [comment]
Hi, just to clarify, everything works fine, but these 4 images, which you sent links for, are **Not solved**, right?

OR: do you receive **Not solved** not only for the images you sent, but just constantly?

Didn't get it, sry. Let me know, thanks!

**Comment by longinteger017** [comment]
Hi, sorry for my miscommunication. 

As for me, the algorithm hasn't solved any captcha yet. I tried like 20 different times and all cases returned **Not Solved**.
It didn't work constantly. Never worked for me.

Do the 4 .jpg work for you?

**Comment by a-maliarov** [comment]
These four links are working fine for me, I assume that the problem is connected to how captcha image is displayed in your browser (because `fromdriver` class method takes a screenshot and then crops the captcha image).

Try another class method - `fromlink`. This will use the captcha image link, therefore it will be not relevant how the image is displayed in the browser.

Here is the example with those four links:
```python
from amazoncaptcha import AmazonCaptcha

links = [
    'https://images-na.ssl-images-amazon.com/captcha/bfhuzdtn/Captcha_cebmxydbrt.jpg',
    'https://images-na.ssl-images-amazon.com/captcha/perumqgc/Captcha_gaommpndkq.jpg',
    'https://images-na.ssl-images-amazon.com/captcha/rhnrlggh/Captcha_tijaodpupx.jpg',
    'https://images-na.ssl-images-amazon.com/captcha/bysppkyq/Captcha_xroxbnvmrg.jpg'
]

for link in links:    
    captcha = AmazonCaptcha.fromlink(link)
    print(captcha.solve())
```

**Comment by a-maliarov** [comment]
So, in your code, when you are on the page with captcha, instead of using `fromdriver`, firstly extract the captcha image link and then use `fromlink`. Since it is the first `img` at the page, it is not obligatory to use BautifulSoup, but you can do the extraction your way. The main point is to just get the captcha link.

Here is the example of what I mean:
```python
from webdriver_manager.chrome import ChromeDriverManager
from amazoncaptcha import AmazonCaptcha
from selenium import webdriver

driver = webdriver.Chrome(ChromeDriverManager().install())
driver.get('https://www.amazon.com/errors/validateCaptcha')

captcha_link = driver.page_source.split('<img src="')[1].split('">')[0]   # extract captcha link
captcha = AmazonCaptcha.fromlink(captcha_link)                               # pass it to `fromlink` class method
print(captcha.solve())
```

**Comment by longinteger017** [comment]
Perfect solution and explanation. Just tested it. Works like a charm. 

Thank you very much!

**Comment by a-maliarov** [comment]
No problems, have a great day!

**Comment by Dohzer43** [comment]
This solution also worked for me! Thank You

**Comment by sfilargi** [comment]
I was hitting the same. @Dohzer43 @longinteger017 can you verify if you are using a high DPI monitor with DPI scaling?

In my case the problem seems to be that in `fromdriver` we do the following:

```
        location = element.location
        size = element.size
        left = location['x']
        top = location['y']
        right = location['x'] + size['width']
        bottom = location['y'] + size['height']
```

But because my monitor is configured for high dpi + dpi scaling, the coordinates were not matching to the PNG captured. Multiplying everything by 2, solved the issue.
