### ISSUE TITLE
Unable to import Amazon captcha

### ISSUE THREAD

**Issue by sureshvigneshbe** [a-maliarov/amazoncaptcha#33]
Hi Team.
from amazoncaptcha import AmazonCaptcha or import amazoncaptcha in python 3.5.0

Is there any way to make compatible for python 3.5 version.kindly assist.

Recently installed python 3.6 version.But still the same error.Could you help on this.

Getting below error : 

![image](https://user-images.githubusercontent.com/54659999/103401376-8d0f2d80-4b6e-11eb-8edc-22e226c95178.png)

Could you please help on the issue.

**Comment by a-maliarov** [comment]
Hi, sorry, but Python 3.5 support was dropped the same time Pillow library has stopped supporting this version of Python.

Unfortunately, it will not be possible to implement a solution for Python 3.5 since it's not just about f-strings (the problem in the screenshot), but also about the way solver cracks captchas.
