### ISSUE TITLE
[help]

### ISSUE THREAD

**Issue by Geeero** [a-maliarov/amazoncaptcha#35]
**Describe the bug**
I tryed to install amazoncaptcha with the pip command but when i try to execute my .py i got this error "line 1, in <module>
    from amazoncaptcha import AmazonCaptcha
ModuleNotFoundError: No module named 'amazoncaptcha'
"

**To Reproduce**
I followed the guide to install it

**Desktop (please complete the following information):**
 - OS: [W10]
 - Browser [chrome]
 - Version [88]

**Comment by a-maliarov** [comment]
Hi, it seems like there was a problem while installing the library.

First of all, try to install any library that you haven't had before on your computer and check if you can import it. If everything works fine, then we can agree that `amazoncaptcha` is the reason here.

If it is indeed, then type `pip uninstall amazoncaptcha` in your console. The final console logs row should be `Successfully uninstalled amazoncaptcha-0.5.0`. Then type `pip install amazoncaptcha`, where the result should be `Successfully installed amazoncaptcha-0.5.0`.

After these 2 steps are done, try to import `amazoncaptcha` again in your .py file. If there was an unpredicted scenario, while doing these two steps, write me back here pointing the difference out. Thanks!
