### ISSUE TITLE
Curious about the scope of your project

### ISSUE THREAD

**Issue by schabertrobbinger** [a-maliarov/amazoncaptcha#36]
First of all, I think that captcha solving is a really cool application of machine learning techniques. I am interested in making a simple web app to present the results of a data science project carried out using cached Amazon review data from a couple of years ago when it was easier to scrape the site. The idea of the web app will be that a scrape will happen in real time for a particular product and then the model I have built will be applied to make a guess about which reviews are the most relevant to making an informed purchasing decision. Amazon's antiscraping defenses are such that it seems that I will have to either pay for a VPN to cycle IPs or find a way to robustly solve captchas. Is your tool able to solve captchas and hand the solutions over to Amazon using pyppeteer or some other tool in a way which will satisfy the site and allow me access to the source code of the page I actually want to visit? If so, do you have sample code for this? I am very new to python and it is not obvious to me how to do this from the sample code you presented on your home page. If this is not currently feasible, is there a chance that it could be made so in the near future? I do not need this to work on an industrial scale; the app will only be used sporadically as a proof-or-concept demonstration of the machine learning I have done. If this is not something that you are interested in, no problem. In that case, I would be curious to know what applications you have in mind for your program? I suppose that the challenge of building something which can pass "Turing tests" is a worthy goal in and of itself :)

**Comment by jo3p** [comment]
> Is your tool able to solve captchas and hand the solutions over to Amazon using pyppeteer or some other tool in a way which will satisfy the site and allow me access to the source code of the page I actually want to visit? If so, do you have sample code for this? 

Hi @schabertrobbinger. What I think you are looking for is access to a specific Amazon product page and you ask for code how to do this? I see on your GitHub page you mainly use Flask and the builtin requests package to do the scraping. I can highly recommend [Selenium](https://selenium-python.readthedocs.io) as well. Selenium requires a web driver, I'd recommend [chromedriver](https://chromedriver.chromium.org/getting-started) given that most people have Google Chrome installed on their computer anyways.

Anyhow, I think the [README](https://github.com/a-maliarov/amazoncaptcha/blob/master/README.md) does a really good job in explaining the one-line usage of the amazoncaptcha package. 

```python
from amazoncaptcha import AmazonCaptcha

link = 'https://images-na.ssl-images-amazon.com/captcha/usvmgloq/Captcha_kwrrnqwkph.jpg'

captcha = AmazonCaptcha.fromlink(link)
solution = captcha.solve()
```



The "link" in this snippet should be extracted from the webpage. Fortunately, @a-maliarov already provided us with a simple way to do this [here](https://github.com/a-maliarov/amazoncaptcha/issues/27#issuecomment-716211789): 

```python
from amazoncaptcha import AmazonCaptcha
from selenium import webdriver

driver = webdriver.Chrome()
driver.get('https://www.amazon.com/errors/validateCaptcha')

captcha_link = driver.page_source.split('<img src="')[1].split('">')[0]   # extract captcha link
captcha = AmazonCaptcha.fromlink(captcha_link)                            # pass it to `fromlink` class method
solution = captcha.solve()
```

This snippet returns a string with the solution to the CAPTCHA. This is an awesome result in itself, but should be filled in the appropriate field in order to continue to the actual product page. The way I've implemented this is in my workflow is as follows:

```python
fill_captcha_element = driver.find_element_by_id('captchacharacters')  # this finds the fill-form-field on the webpage
fill_captcha_element.send_keys(solution)  # this "types in" the solution characters
fill_captcha_element.send_keys(Keys.RETURN)  # this presses the enter/return key on your keyboard to submit the solution.
```

Please let me know if this rather technical solution to your question is of any use.

**Comment by schabertrobbinger** [comment]
Absolutely, yes, thank you very much for the detailed response to my query.

**Comment by a-maliarov** [comment]
Hi, sorry for the late response, I wasn't able to answer during last months due to some reasons.

Thank you, @jo3p, for answering this one for me! Have a great day!

**Comment by jo3p** [comment]
> Hi, sorry for the late response, I wasn't able to answer during last months due to some reasons.
> 
> Thank you, @jo3p, for answering this one for me! Have a great day!

Sure no problem! I should thank you for this awesome package!! :)
