### ISSUE TITLE
The solver doesn't work with modified images of captcha

### ISSUE THREAD

**Issue by abadallah** [a-maliarov/amazoncaptcha#82]
Hello
 I have an image with np array format and save it with a PIL image with formatting jpg after that I pass the image to the solver but every time I receive "Not solved" 
![Screenshot_4](https://user-images.githubusercontent.com/32160285/224581713-f9afb6e7-51fa-4762-ad4c-3b9d98370208.png)

![Screenshot_5](https://user-images.githubusercontent.com/32160285/224581760-c6e1ccfe-4cdf-436d-8ec1-1cd8e69ae96e.png)

I can't figure out what the problem is, I tried to download and try images from amazon it worked well so can anyone help me 

PIL version '9.2.0'
python version '3.9.13'

**Comment by a-maliarov** [comment]
The library recognizes the letters in the image by pixel patterns, because the original captcha always has the same size. 

I'm not sure how you were able to download the captcha image not in 200x70 and why you need to resize it, but, simply answering your question - the library doesn't work in this case cause you are not providing the original image of captcha. Try removing `resize` method, `quality`, `optimize`, and `progressive` parameters.

**Comment by abadallah** [comment]
Hello, thanks for the replay

I updated my code like what you mentioned but it doesn't work so let me clarify my problem more. 

in my case, I have the numpy.array of the image and it is different in size rather than the original image so I followed these steps

read np.array --> convert it to PIL image --> Save as new image as ".jpag" --> pass the new image to the solver

and I tested it with a downloaded image from amazon with this step

download image --> read it with PIL --> save it with PIL --> pass the saved one to the solver

I believe that this repo is the best one with amazon OCR with a fast response so I will be glade if you can help me to figure out the problem
